FROM node:18.12.1-bullseye-slim AS development
ENV botToken MTA0MzUwODI5MTU2Njg0NTk2Mg.GiG0iK.EWtJEbnyx5s27uXwTdg0jbCFm0r8L5TClgimhc
ENV guildId 973030479009812490/973268795357552640
ENV enviroment debug
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm install
EXPOSE 4005
CMD ["npm","run","start:dev"]