FROM node:18.12.1-bullseye-slim AS development
ENV botToken token
ENV guildId clientId
ENV enviroment debug
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm install
EXPOSE 4005
CMD ["npm","run","start:dev"]