version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    ports:
      - 4000:80